### ISSUE TITLE
bash: /notebooks#: No such file or directory

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/HistomicsML-TA#60]
I am trying to set up a dataset.

I followed the steps of creating a dataset using the instructions in https://histomicsml2.readthedocs.io/en/latest/data-create.html
and using a sample image from the Openslide website. (http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-JP2K-33005.svs).

Next, I tried to import the dataset using the instructions in 
https://histomicsml2.readthedocs.io/en/latest/data-import.html#data-import.
I completed the steps up to **Launch HistomicsML2 and import the datasets**
After that when I type in 
`/notebooks# ln -s /datasets/classifiers /var/www/html/HistomicsML/trainingsets`
I get 
`bash: /notebooks#: No such file or directory`

What am I doing wrong? Thanks in advance.

**Comment by slee172** [comment]
It seems like you don't have a directory to link. The error "No such file or directory" is caused by missing directory. Try to check if you correctly mount the directory "/datasets/classifiers" on your docker image. Or, you can just check if there is a directory "/var/www/html/HistomicsML/trainingsets".

**Comment by Reasat** [comment]
Thanks for the reply! It seems the "/var/www/html/HistomicsML/trainingsets" does not exist. How is that folder created?

**Comment by slee172** [comment]
@Reasat I just wanted to make sure that whether you already created a directory "/var/www/html/HistomicsML/trainingsets" or not on your docker image. The "ln -s sourceFile targetFile" command will create a symbol link for sourceFile. I remember that the docker image already has the directory "/var/www/html/HistomicsML". So, you don't need to create the "/var/www/html/HistomicsML/trainingsets" because the "ln" command will create the "trainingsets" link under the directory. What you could do is to confirm that you have the directory "/datasets/classifiers" mounted on your docker image.

**Comment by Reasat** [comment]
![image](https://user-images.githubusercontent.com/15989033/95899895-d1044a80-0d56-11eb-89ad-75cb716e80e7.png)
I can see the `/datasets/classifiers` folder from the terminal after I do `docker run`. Does it mean it's mounted? (Apologies, not familiar with docker)

**Comment by slee172** [comment]
Good to know that it seems like you correctly mounted the dataset folder. Can you check if you have the directory "/var/www/html/HistomicsML" ? If you have it, the command "ln -s ... " should create a link for "/datasets/classifiers".

**Comment by Reasat** [comment]
Thanks! My bad, I thought the `/notebook` portion was part of the command.
I have finished creating the dataset and my project directory structure looks like this
![image](https://user-images.githubusercontent.com/15989033/95921549-189ace80-0d77-11eb-9a82-7e71564fda55.png)
I think I have to select 'myproject' as the base project 
However, I don't see the option in `http://localhost/HistomicsML/data.html`
![Screenshot from 2020-10-13 17-21-51](https://user-images.githubusercontent.com/15989033/95922374-c35fbc80-0d78-11eb-9ef5-cbf79f50dcbd.png)

**Comment by slee172** [comment]
I think the issue "bash: /notebooks#: No such file or directory" has been resolved. 

Let me create the data import issue as another issue.
