### ISSUE TITLE
Prediction for all superpixels

### ISSUE THREAD

**Issue by Reasat** [CancerDataScience/HistomicsML-TA#71]
How can I extract predictions for all of the superpixels from the classifier?

In the example BRCA dataset, after I finish the active learning part and hit finalize, I navigate to the reports tab. 
![Screenshot from 2020-11-30 00-06-13](https://user-images.githubusercontent.com/15989033/100574596-fcf47480-329f-11eb-8007-635293dca511.png)

`Slide summary inference` gives the number of positive and negative superpixels. The .h5 file from the `Download classifier` section only contains superpixel information that I have manually annotated but does not contain info about the predictions.

But I don't see the `predict slides` portion as reported in the docs
https://histomicsml2.readthedocs.io/en/latest/reports.html
Also, the **Command-line tools** part of the doc is not very clear. It says to execute `docker run` to create results for superpixel inference. Shouldn't there be another argument after docker run? And how do I proceed to make this work for the example BRCA dataset?

**Comment by slee172** [comment]
@Reasat In order to avoid a huge amount of memory consumption, we provide a command-line tool with some parameters. For this, I just updated a python script "generate_mask_cmd.py" [here](https://github.com/CancerDataScience/HistomicsML2/blob/master/predict-rest-api/generate_mask_cmd.py#L24), so you download and use it for generating the entire mask. You can also generate a mask (ROI) using the "Mask Image Inference" for the prediction.
FYI, here's a rough instruction for you to use the code.
1. Download the generate_mask_cmd.py
2. Copy generate_mask_cmd.py to your docker image 
i.e) docker cp generate_mask_cmd.py de5a17376f57:/var/www/html/predict-rest-api/
(de5a17376f57 is a CONTAINER ID of cancerdatascience/histomicsml:examle)
3. Go to the container and run the code.
i.e) python generate_mask_cmd.py /datasets/BRCA/BRCA-spfeatures-1.h5 /datasets/models/test.h5 /datasets/BRCA/tif/TCGA-A2-A3XS-01Z-00-DX1.svs.dzi.tif ./
(The first parameter is the dataset, the second parameter is a model you created, the third parameter is the location of the slide, the fourth parameter is the location of the output file).
There are more parameters you can use in the code. Hope this would help you.
